# Game Theory


In [2]:
# install nashpy

!pip install nashpy

  Attempting uninstall: numpy
    Found existing installation: numpy 1.20.1
    Uninstalling numpy-1.20.1:
      Successfully uninstalled numpy-1.20.1


In [3]:
import nashpy as nash

In [4]:
nash.__version__

'0.0.35'

In [5]:
A = [[3,1], [0,2]]
B = [[2,1], [0,3]]
battle_of_the_sexes = nash.Game(A, B)

In [6]:
battle_of_the_sexes

Bi matrix game with payoff matrices:

Row player:
[[3 1]
 [0 2]]

Column player:
[[2 1]
 [0 3]]

In [9]:
# matching pennies
A = [[1,-1],[-1,1]]
B = [[-1,1],[1,-1]]

matching_pennies = nash.Game(A,B)

In [10]:
matching_pennies

Zero sum game with payoff matrices:

Row player:
[[ 1 -1]
 [-1  1]]

Column player:
[[-1  1]
 [ 1 -1]]